FROM node:20-alpine AS builder

WORKDIR /app
COPY package*.json ./
RUN npm ci

COPY . .
ENV VITE_API_URL=https://order-packs-calculator-api.herokuapp.com
RUN npm run build

FROM node:20-alpine
WORKDIR /app
RUN npm install -g serve

COPY --from=builder /app/dist ./dist
EXPOSE 5000

CMD ["serve", "-s", "dist", "-l", "5000"]
